eps: 0.001
eval_mode: false
#eval_mode: true

# optimizer
lr: 0.0001

# train
data_dir: 'DanceTrack/trackers_gt'
diffnet: HMINet
interval: 5
augment: true
encoder_dim: 256
tf_layer: 3
epochs: 800
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0]

# Validation (during training)
eval_at: 800
det_dir: 'detections'
info_dir: 'DanceTrack/val'
reid_dir: 'cache/embeddings'
save_dir: 'results/yolov10n_diffmot_train'
eval_expname: 'yolov10n_diffmot_train'
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
